[tool.poetry]
name = "taxi-demand-predictor"
version = "0.1.0"
description = ""
authors = ["marendra <marendra79@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
